---
  - name: OpenIndiana - Install Jenkins Swarm Client Service
    template: src=templates/jenkins-swarm-client.sh.j2 dest=/etc/init.d/jenkins-swarm-client mode=0755

  - name: OpenIndiana - Start Jenkins Swarm Client Service
    shell: nohup /etc/init.d/jenkins-swarm-client start
