---
- defaults:
    name: global
    node: swarm
    logrotate:
        daysToKeep: 14
        numToKeep: 32
        artifactDaysToKeep: 14
        artifactNumToKeep: 32
    wrappers:
        - ansicolor:
            colormap: xterm
