---
# global defaults that get applied to every project/job/whatever.
# We use ansicolor for fancy text output during the compile phase.
- defaults:
    name: global
    properties:
        - build-discarder:
            days-to-keep: 90
            num-to-keep: 64
            artifact-days-to-keep: 7
            artifact-num-to-keep: 32
    wrappers:
        - ansicolor:
            colormap: xterm
    publishers:
        - build-publisher:
            publish-unstable-builds: true
            publish-failed-builds: true
            days-to-keep: 32
            num-to-keep: 128
        - warnings:
            console-log-parsers:
                - Clang (LLVM based)
                - GNU Make + GNU C Compiler (gcc)
                - GNU C Compiler 4 (gcc)
