---
- job-template:
    name: '{name}'
    project-type: matrix
    axes:
      - axis:
          type: slave
          name: nodes
          values:
              - FreeBSD
              - Ubuntu
              - Debian
              - OpenBSD
    scm:
      - git:
          url: '{url}'
          branches:
              - origin/master
          wipe-workspace: true
          skip-tag: true
          per-build-tag: false
          git-config-name: "Xfce Buildbot"
          git-config-email: "nobody@localhost"
    builders:
      - shell: |
          #!bash -l
          PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/libdata/pkgconfig:/usr/lib/pkgconfig
          LD_LIBRARY_PATH=/usr/local/lib:/usr/lib
          PATH=/usr/gnu/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/usr/gnu/bin:/bin:/usr/X11R6/bin
          LDFLAGS="-L/usr/lib -L/usr/local/lib"
          export PATH
          export PKG_CONFIG_PATH
          export LD_LIBRARY_PATH
          export LDFLAGS
          unamestr=`uname`
          if [[ $unamestr == OpenBSD ]]; then
            AUTOMAKE_VERSION=1.15
            AUTOCONF_VERSION=2.69
            export AUTOMAKE_VERSION
            export AUTOCONF_VERSION
            export CC=clang
          fi
          if [[ -f autogen.sh ]]; then
            echo -e "\e[31m running: ./autogen.sh \e[0m"
            ./autogen.sh --enable-debug=yes $option
          elif [[ -f configure ]]; then
            echo -e "\e[31m running: ./configure \e[0m"
            ./configure
          elif [[ -f CMakeLists.txt ]]; then
            echo -e "\e[31m running: cmake . \e[0m"
            cmake .
          else
                echo -e "\e[31m Unknown build system \e[0m"
          fi
          if [[ $unamestr == *BSD* ]] || [[ $unamestr == DragonFly ]] || [[ $unamestr == SunOS ]]; then
                  echo -e "\e[31m running: gmake \e[0m"
                  gmake
                  echo -e "\e[31m running: gmake install \e[0m"
                  gmake install
          else
                  echo -e "\e[31m running: make \e[0m"
                  make
                  echo -e "\e[31m running: make install \e[0m"
                  sudo make install
          fi
