---
# This job template builds all of the Xfce Core project in stages
# based on every component's dependencies. Projects that have the
# same common dependencies like garcon-exo-and-tumbler get put in
# the same stage. The individual projects are located in the Xfce
# project grouping in the projects.yml file.
- job-template:
    name: Xfce-Core
    project-type: multijob
    concurrent: true
    triggers:
        - timed: "@daily"
    builders:
        - multijob:
            name: xfce4-dev-tools
            condition: ALWAYS
            projects:
                - name: xfce4-dev-tools
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: libxfce4util
            condition: ALWAYS
            projects:
                - name: libxfce4util
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: xfconf
            condition: ALWAYS
            projects:
                - name: xfconf
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: libxfce4ui
            condition: ALWAYS
            projects:
                - name: libxfce4ui
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: garcon-exo-and-tumbler
            condition: ALWAYS
            projects:
                - name: garcon
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: exo
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: tumbler
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: thunar
            condition: ALWAYS
            projects:
                - name: thunar
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: xfce-core-others
            condition: ALWAYS
            projects:
                - name: xfdesktop
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-appfinder
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-panel
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-power-manager
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-settings
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfwm4
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-session
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: xfce-apps
            condition: ALWAYS
            projects:
                - name: gigolo
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: parole
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: ristretto
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-panel-profiles
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-notifyd
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-screensaver
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-screenshooter
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-taskmanager
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-terminal
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfdashboard
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: mousepad
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-dict
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-volumed-pulse
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfmpc
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: thunar-plugins
            condition: ALWAYS
            projects:
                - name: thunar-archive-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: thunar-media-tags-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: thunar-shares-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: thunar-vcs-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: thunarx-python
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true
        - multijob:
            name: xfce-plugins
            condition: ALWAYS
            projects:
                - name: xfce4-battery-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-calculator-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-clipman-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-cpufreq-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-datetime-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-diskperf-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-embed-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-eyes-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-fsguard-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-generic-slider
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-genmon-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-hardware-monitor-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-indicator-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-mount-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-mount-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-mpc-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-sensors-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-pulseaudio-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-netload-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-notes-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-places-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-smartbookmark-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-systemload-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-verve-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-wavelan-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-weather-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-whiskermenu-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true

                - name: xfce4-xkb-plugin
                  kill-phase-on: NEVER
                  abort-all-job: false
                  current-parameters: true



# This project creates the Xfce-Core multijob you see in Jenkins
# from the similarly named Xfce-Core job template above.
- project:
    name: Xfce-Core
    jobs:
      - Xfce-Core
