---
- project:
    name: Xfce-Core
    jobs:
      - '{name}_job':
          name: xfce4-dev-tools
          url: git://git.xfce.org/xfce/xfce4-dev-tools
      - '{name}_job':
          name: libxfce4util
          url: git://git.xfce.org/xfce/libxfce4util
      - '{name}_job':
          name: libxfce4ui
          url: git://git.xfce.org/xfce/libxfce4ui
      - '{name}_job':
          name: xfconf
          url: git://git.xfce.org/xfce/xfconf
      - '{name}_job':
          name: exo
          url: git://git.xfce.org/xfce/exo
      - '{name}_job':
          name: garcon
          url: git://git.xfce.org/xfce/garcon
      - '{name}_job':
          name: tumbler
          url: git://git.xfce.org/xfce/tumbler
      - '{name}_job':
          name: xfwm4
          url: git://git.xfce.org/xfce/xfwm4
      - '{name}_job':
          name: xfce4-session
          url: git://git.xfce.org/xfce/xfce4-session
      - '{name}_job':
          name: xfce4-settings
          url: git://git.xfce.org/xfce/xfce4-settings
      - '{name}_job':
          name: thunar
          url: git://git.xfce.org/xfce/thunar
      - '{name}_job':
          name: xfdesktop
          url: git://git.xfce.org/xfce/xfdesktop
      - '{name}_job':
          name: xfce4-appfinder
          url: git://git.xfce.org/xfce/xfce4-appfinder
      - '{name}_job':
          name: xfce4-panel
          url: git://git.xfce.org/xfce/xfce4-panel
      - '{name}_job':
          name: xfce4-power-manager
          url: git://git.xfce.org/xfce/xfce4-power-manager
