---
# All of the individual Xfce projects are here. They get grouped into
# multijobs.yml and use the job-template.yml.
- project:
    name: Xfce
    jobs:
      - '{name}':
          name: xfce4-dev-tools
          url: git://git.xfce.org/xfce/xfce4-dev-tools
      - '{name}':
          name: libxfce4util
          url: git://git.xfce.org/xfce/libxfce4util
      - '{name}':
          name: libxfce4ui
          url: git://git.xfce.org/xfce/libxfce4ui
      - '{name}':
          name: xfconf
          url: git://git.xfce.org/xfce/xfconf
      - '{name}':
          name: exo
          url: git://git.xfce.org/xfce/exo
      - '{name}':
          name: garcon
          url: git://git.xfce.org/xfce/garcon
      - '{name}':
          name: tumbler
          url: git://git.xfce.org/xfce/tumbler
      - '{name}':
          name: thunar
          url: git://git.xfce.org/xfce/thunar
      - '{name}':
          name: xfdesktop
          url: git://git.xfce.org/xfce/xfdesktop
      - '{name}':
          name: xfce4-appfinder
          url: git://git.xfce.org/xfce/xfce4-appfinder
      - '{name}':
          name: xfce4-panel
          url: git://git.xfce.org/xfce/xfce4-panel
      - '{name}':
          name: xfce4-power-manager
          url: git://git.xfce.org/xfce/xfce4-power-manager
      - '{name}':
          name: xfce4-settings
          url: git://git.xfce.org/xfce/xfce4-settings
      - '{name}':
          name: xfwm4
          url: git://git.xfce.org/xfce/xfwm4
      - '{name}':
          name: xfce4-session
          url: git://git.xfce.org/xfce/xfce4-session

- job:
    name: ConsoleKit2
    project-type: matrix
    axes:
      - axis:
          type: slave
          name: nodes
          values:
              - FreeBSD
              - Ubuntu
              - Debian
              - OpenBSD
    scm:
      - git:
          url: https://github.com/ConsoleKit2/ConsoleKit2.git
          branches:
              - origin/master
          wipe-workspace: false
          skip-tag: true
          per-build-tag: false
          git-config-name: "Xfce Buildbot"
          git-config-email: "nobody@localhost"
    triggers:
      - pollscm:
          cron: "H/30 * * * *"
          ignore-post-commit-hooks: True
    builders:
      - shell: |
          #!bash -l
          PKG_CONFIG_PATH=/usr/local/libdata/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
          LD_LIBRARY_PATH=/usr/local/lib:/usr/lib
          export PKG_CONFIG_PATH
          export LD_LIBRARY_PATH
          unamestr=`uname`
          echo -e "\e[31m running: ./autogen.sh \e[0m"
          ./autogen.sh
          if [[ $unamestr == *BSD* ]] || [[ $unamestr == DragonFly ]]; then
                  echo -e "\e[31m running: gmake \e[0m"
                  gmake
          else
                  echo -e "\e[31m running: make \e[0m"
                  make
          fi
