---
jenkins_user:  'jenkins'
jenkins_group: 'jenkins'
jenkins_home:  "/var/lib/{{jenkins_user}}"
jenkins_workspace: "{{jenkins_home}}/workspace"

jenkins_hostname: 10.10.10.10
jenkins_http_port: 8080
jenkins_url_prefix: /
jenkins_full_url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"

jenkins_plugins: [swarm, git, jenkins-multijob-plugin, matrix-project, build-publisher, ansicolor, warnings]
jenkins_plugin_timeout: 600
jenkins_package_state: latest

jenkins_admin_username: 'admin'
jenkins_admin_password: 'admin'

swarm_client_version: 3.4

openbsd_java_version: 1.8.0

java_path: ""
