---
# install packages. We use state=present because FreeBSD doesn't like latest
        - name: Install packages
          package: name={{ item }} state=present
          with_items:
                - git
                - autoconf
                - automake
                - bash
