---
  - name: Create Jenkins system user
    user: name={{jenkins_user}} home={{jenkins_home}} system=yes
          generate_ssh_key=yes

  - name: Create Jenkins workspace directory
    file: name={{jenkins_workspace}}
          owner={{jenkins_user}}
          group={{jenkins_user}}
          state=directory

  - name: Configure sudoers for Jenkins system user
    lineinfile: dest="/etc/sudoers.d/{{jenkins_user}}"
                line="{{jenkins_user}} ALL=(ALL) NOPASSWD:ALL"
                state=present
                create=yes
                mode=0440
                validate='visudo -cf %s'

  - name: Create Jenkins Swarm Client directory
    file: >
        path=/opt/jenkins-swarm-client
        owner={{jenkins_user}}
        group={{jenkins_user}}
        mode=0755
        state=directory

  - name: Download Jenkins Swarm Client
    get_url: >
        url=https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ swarm_client_version }}/swarm-client-{{ swarm_client_version }}.jar
        dest=/opt/jenkins-swarm-client/swarm-client-{{ swarm_client_version }}.jar

  - include: tasks/ubuntu-swarm-client-install.yml
    when: ansible_os_family == "Debian"

  - include: tasks/freebsd-swarm-client-install.yml
    when: ansible_os_family == "FreeBSD"
