---
  - name: FreeBSD - Install Jenkins Swarm Client Service
    template: src=templates/freebsd-jenkins-swarm-client.sh.j2 dest=/usr/local/etc/rc.d/jenkins_swarm_client mode=0755

  - name: FreeBSD - Start Jenkins Swarm Client Service
    service:
        name: jenkins_swarm_client
        enabled: yes
        state: started
        use: service
