---
- name: DragonFlyBSD Setup Playbook
  hosts: DragonFlyBSD
  become: yes
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/common_vars.yml

  pre_tasks:
    - name: install python2, ansible requires it
      raw: test -e /usr/local/bin/python || (pkg install -qy python)
      register: output
      changed_when: output.stdout != ""
      tags: always

    - name: gather facts
      setup:

  tasks:
    - include: tasks/freebsd/builder-package-install.yml
    - include: tasks/dragonflybsd/dfly-jenkins-builder-setup.yml
    - include: tasks/freebsd/swarm-client-install.yml
