---
- name: Jenkins Master Setup Playbook
  hosts: Jenkins
  become: yes
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/common_vars.yml

  pre_tasks:
    - name: install python2, ansible requires it
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always

    - name: gather facts
      setup:

    - name: install common dependencies
      include: tasks/common-install.yml

  roles:
    - ansible-role-jenkins

  tasks:
    - name: install packages needed by the jenkins master
      include: tasks/jenkins/jenkins-master-package-install.yml

    - name: install Jenkins Job Builder
      pip:
        name: jenkins-job-builder
        state: latest

    - include: tasks/jenkins/jenkins-jobs-ini-install.yml

    - name: add the jobs to jenkins
      command: jenkins-jobs update --delete-old /vagrant/ansible/jenkins-jobs

    - name: "restart Jenkins"
      service: name=jenkins state=restarted
