---
- name: Jenkins Master Setup Playbook
  hosts: Jenkins
  become: yes
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/common_vars.yml

  pre_tasks:
    - name: install python2, ansible requires it
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always

    - name: gather facts
      setup:

    - name: install dependencies
      include: tasks/common-install.yml

  roles:
    - ansible-role-jenkins

  tasks:
    - name: "restart Jenkins"
      service: name=jenkins state=restarted
