---
- name: OpenIndiana Setup Playbook
  hosts: OpenIndiana
  become: yes
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/common_vars.yml

  tasks:
    - include: tasks/openindiana/builder-package-install.yml
    - include: tasks/jenkins-builder-setup.yml
    - include: tasks/openindiana/swarm-client-install.yml
