---
- name: OpenBSD Setup Playbook
  hosts: OpenBSD
  become: yes
  remote_user: root
  gather_facts: yes

  vars_files:
    - vars/common_vars.yml

  tasks:
    - include: tasks/common-install.yml
    - include: tasks/openbsd/builder-package-install.yml
    - include: tasks/jenkins-builder-setup.yml
    - include: tasks/openbsd/swarm-client-install.yml
