---
- import_playbook: dragonflybsd-playbook.yml
- import_playbook: freebsd-playbook.yml
- import_playbook: jenkins-playbook.yml
- import_playbook: openbsd-playbook.yml
- import_playbook: openindiana-playbook.yml
- import_playbook: ubuntu-playbook.yml
